### ISSUE TITLE
How is R3 tested?

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#20]
From SRS:
> R3: During the calculation, the software should be capable of handling situations where units do not match.

In VnV it is mentioned that tests in 4.1.2 covers R3, but the tests here are more about if the software follows proper steps to implement the models, rather than handling units discrepancies. I imagine R3 is verified like intentionally feeding data with incompatible units and see if the software can still sort things out and produce the correct output.

**Comment by CynthiaLiu0805** [comment]
Probably I was not clear enough in R3, I was trying to say the software should handle the unit not matching in between steps. For example, the unit for the result of step 1 is different from the unit for input needed for step two and the software should handle that. And because section 4.1.2 is automatic with the input models, the developers can not manually feed data halfway.
