### ISSUE TITLE
4.4.5 instance models

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#27]
An interpolation theory?
Add text to explain how the weather data and traffic data come in.
A refinement for how the parts fit together?

**Comment by CynthiaLiu0805** [comment]
Hi Dr. Smith@smiths ,

Could you give some more explanation or comments on the feedback of [SRS](https://github.com/CynthiaLiu0805/BridgeCorrosion/blob/main/docs/SRS/SRS.pdf) 4.4.5? What do you mean by interpolation theory and refinement for how parts fit together?

Thanks,
Cynthia

**Comment by smiths** [comment]
My comment was because I feel like there should be a theory that allows you to interpolate the data between the grid points where you know it and the point where the user is requesting data.  Isn't this something that the software currently does?  If I'm right, you should add a theory related to 2d interpolation.  The theory of [repeated linear interpolation](https://en.wikipedia.org/wiki/Bilinear_interpolation) should be fine, at least to start.
