### ISSUE TITLE
VnV 4.1.2 Intermediate Tests

### ISSUE THREAD

**Issue by CynthiaLiu0805** [CynthiaLiu0805/BridgeCorrosion#30]
These tests might be more suitable for unit testing - will move them to that section after implementation.
Also need to look at Matlab unit testing? Is there such a thing?

**Comment by smiths** [comment]
Yes, you can do [unit tests in Matlab](https://www.mathworks.com/help/matlab/matlab_prog/ways-to-write-unit-tests.html).  Is there a reason you are using Matlab?  I'm not saying it isn't a good choice, but it is awkward for software design.  Is there anything you need to do that you can't do in Python?  If Dr. Yang uses Matlab, it could just be because her team already knows Matlab.

**Comment by CynthiaLiu0805** [comment]
> Yes, you can do [unit tests in Matlab](https://www.mathworks.com/help/matlab/matlab_prog/ways-to-write-unit-tests.html). Is there a reason you are using Matlab? I'm not saying it isn't a good choice, but it is awkward for software design. Is there anything you need to do that you can't do in Python? If Dr. Yang uses Matlab, it could just be because her team already knows Matlab.

Yes, the main reason that I am using Matlab is because Dr. Yang is using it and I thought it would be easier for them to understand and maintain it in the future. Would you mind explaining why it is awkward to use Matlab for software design, because it separates the entire software into two coding languages?

**Comment by CynthiaLiu0805** [comment]
Fixed in [60a803b](https://github.com/CynthiaLiu0805/BridgeCorrosion/commit/60a803bcb11c410a43de5db6295328ee1540a05e) by changing the coding langauge to Python.
