### ISSUE TITLE
MG: Decomposing of M7

### ISSUE THREAD

**Issue by omltcat** [CynthiaLiu0805/BridgeCorrosion#45]
> Chloride Exposure Calculation Module (M7)

I understand that you probably have already finished this module with POC so you want to keep it as is. But consider this:

1. According to your SRS, the calculation of chloride exposure involves quite a few different theorem/models. Each of them can be a "secret" of itself and changed individually. For example, maybe someone suggest a different way to calculate splash, or maybe it is necessitated by a new dataset. Do you really want to keep them all bundled together?
2. AC2 talks about data changes every year. It may be a good idea to at least separate this part. Have one module whose entire job is to feed data to the calculation module. The calculation module does not need to worry about where the data comes from, if it is updated manually or automatically.

**Comment by CynthiaLiu0805** [comment]
Yes, I know the best option is to separate them as the calculation process contains six steps, but when in POC doing it in Matlab I was not sure how to separate modules (truth: didn't have time). Also in #30 Dr. Smith mentioned if Python would be a better choice for this section. I will have a look at it to see if it is possible to put this module into Python if time is allowed, so that it will have better maintainability.

**Comment by CynthiaLiu0805** [comment]
Fixed in f44c978770eba4675dfa931a8d2ebd225d60bbaa by separating each steps
