### ISSUE TITLE
MG + MIS -Some Modules Misclassified as Abstract Data Type

### ISSUE THREAD

**Issue by rnorouziani** [CynthiaLiu0805/BridgeCorrosion#59]
The M2, M4 and M5 are described as an abstract data type, which seems inaccurate given its functionality.

**Comment by CynthiaLiu0805** [comment]
I misclassified M5 the visualization ad ADT, but I think M2 and M4 should be ADT because I want the input and the searching process(i.e. the result, and the information needed) to be abstract, also for maintainability, if in the future the required input for functions in M2 or M4 changes I don't need to go to everywhere that use that function to modify. Related changes is in [1cbcc74](https://github.com/CynthiaLiu0805/BridgeCorrosion/commit/1cbcc74e04a5cad997aafccaa6df3b5fe5ea7d83)
